// Sector data structures for the procedural universe.
// Each sector represents a deterministic chunk of space defined by (X, Y, Z) coordinates.

use serde::Serialize;

/// Top-level sector output — the "massive JSON" returned to the client.
#[derive(Debug, Serialize)]
pub struct SectorData {
    /// Sector coordinates in the universal grid
    pub coordinates: SectorCoordinates,
    /// Deterministic seed derived from master seed + coordinates
    pub sector_hash: String,
    /// Star system present in this sector (None if void)
    pub star_system: Option<StarSystem>,
    /// Procedural ruins generated via L-Systems
    pub ruins: Vec<Ruin>,
    /// Terrain heightmap samples (flattened NxN grid)
    pub terrain_heightmap: Vec<f64>,
    /// Sector classification for the anti-cheat salt wall (client-side only sees geology)
    pub sector_class: SectorClass,
}

#[derive(Debug, Serialize)]
pub struct SectorCoordinates {
    pub x: i64,
    pub y: i64,
    pub z: i64,
}

#[derive(Debug, Serialize)]
pub struct StarSystem {
    pub star_type: StarType,
    pub luminosity: f64,
    pub temperature_kelvin: u32,
    pub planets: Vec<Planet>,
}

#[derive(Debug, Serialize)]
pub enum StarType {
    RedDwarf,
    YellowMain,
    BlueGiant,
    WhiteDwarf,
    Neutron,
    BlackHole,
}

#[derive(Debug, Serialize)]
pub struct Planet {
    pub name: String,
    pub orbital_radius_au: f64,
    pub mass_earth: f64,
    pub radius_earth: f64,
    pub has_atmosphere: bool,
    pub surface_temperature_k: f64,
    pub biome: Biome,
    pub moons: u8,
}

#[derive(Debug, Serialize)]
pub enum Biome {
    Barren,
    Volcanic,
    Frozen,
    Oceanic,
    Temperate,
    Jungle,
    Desert,
    Toxic,
    Crystalline,
    Biomechanical,
}

/// Procedural ruin generated by L-System grammar derivation.
#[derive(Debug, Serialize)]
pub struct Ruin {
    pub ruin_type: RuinType,
    pub complexity: u32,
    pub age_megayears: f64,
    pub derivation_sequence: String,
}

#[derive(Debug, Serialize)]
pub enum RuinType {
    PrecursorMonolith,
    BiomechanicalHive,
    CrystallineArchive,
    VoidGateway,
    QuantumRelay,
}

/// Client-side sector classification.
/// NOTE: Rarity/loot is NOT included here — that comes from the backend Salt Wall.
#[derive(Debug, Serialize)]
pub enum SectorClass {
    Void,
    Sparse,
    Standard,
    Dense,
    Anomalous,
}
